### ISSUE TITLE
Rename default branch from `master` to `main`

### ISSUE THREAD

**Issue by meyermarcel** [pointlander/peg#153]
This is not so important but it would help to be more conform with the convention and would lower a tiny bit the bar for contributors to this repository.
* All new GitHub repositories use `main` as the default branch
* `git init` gives a hint to change the default branch to `main`
   ```
   hint: Using 'master' as the name for the initial branch. This default branch name
   hint: is subject to change. To configure the initial branch name to use in all
   hint: of your new repositories, which will suppress this warning, call:
   hint:
   hint: 	git config --global init.defaultBranch <name>
   hint:
   hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
   hint: 'development'. The just-created branch can be renamed via this command:
   hint:
   hint: 	git branch -m <name>
   ```
* I am used to type `mai` and hit TAB to let my shell complete to `main`
* `main` could give the contributors the impression that the repository is more up-to-date

Here you can go to the branches of the repository (I didn't find it myself):

<img width="513" alt="Screenshot 2024-11-30 at 12 50 24" src="https://github.com/user-attachments/assets/6ff9c0f9-1892-458d-a612-3e808f269255">

After you changed the default branch name to `main` GitHub will help you with suitable command hints to reflect the change locally as well.
